# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MASTERPANEL.OpenDesktopAuthenticator
PackageVersion: 1.5.1
InstallerType: nullsoft
Scope: user
MinimumOSVersion: 10.0.17763.0
UpgradeBehavior: install
ProductCode: fc7fbb1b-2c01-522b-b761-b3da9a611c1e
AppsAndFeaturesEntries:
  - DisplayName: Open Desktop Authenticator 1.5.1
    Publisher: MASTERPANEL LLC
    DisplayVersion: 1.5.1
InstallerSwitches:
  Custom: /currentuser
ReleaseDate: 2026-09-26
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/opendesktopauthenticator/open-desktop-authenticator/releases/download/v1.5.1/open-desktop-authenticator-1.5.1-x64-setup.exe
    InstallerSha256: FFEAE76596C0262A7392C1DCFD4429E6844C079A068568D773D339356A9C8315
ManifestType: installer
ManifestVersion: 1.12.0
